#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount pacman su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	dwmsi="rm -rf config.h; sudo make clean install" \
	make="make -j12" \
	xclip="xclip -selection clipboard" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	discord='DBUS_SESSION_BUS_ADDRESS="autolaunch:" BROWSER="chromium" discord' \
	wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts" \
	xbindkeys="xbindkeys -f $XDG_CONFIG_HOME/xbindkeys/config" \
	irssi="irssi --config=$XDG_CONFIG_HOME/irssi/config --home="$XDG_DATA_HOME"/irssi" \


# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \


cd_mm_os1() {
	cd /libvirt/debian/home/aleksa/mm_os1 || exit
}

mm_os1() {
	sudo arch-chroot /libvirt/debian /usr/bin/su aleksa -c '/bin/bash -c "cd ~/mm_os1; make qemu"'
}

cd_os1() {
	cd /libvirt/debian/home/aleksa/os1 || exit
}

os1() {
	sudo arch-chroot /libvirt/debian /usr/bin/su aleksa -c '/bin/bash -c "cd ~/os1; make qemu"'
}

os1gdb() {
	sudo arch-chroot /libvirt/debian /usr/bin/su aleksa -c '/bin/bash -c "cd ~/os1; make qemu-gdb"'
}

cd_os2() {
	cd /libvirt/debian/home/aleksa/os2 || exit
}

os2() {
	sudo arch-chroot /libvirt/debian /usr/bin/su aleksa -c '/bin/bash -c "cd ~/os2; make qemu"'
}

# These common commands are just too long! Abbreviate them.
alias \
	sudo="doas" \
	ka="killall" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
	ranger="lf" \
	gdb="gdb -x ~/gdbinit" \
	htop="htop --tree"
